**Breast Cancer Detection with Logistic Regression**

In [ ]:
#importing neccessary libraries
import numpy as np
import sklearn.datasets

In [ ]:
# Loading the dataset 
# Breast_cancer dataset is present on sklearn library
breast_cancer= sklearn.datasets.load_breast_cancer()

In [ ]:
print(breast_cancer)

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]]), 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
 

**Defining the target and input variable from dataset**
*   In this problem finding out the nature of cancer i.e. malignant or benign is our target variable
*   All other data columns act as input variable which will define our solution



In [ ]:
X=breast_cancer.data
Y=breast_cancer.target

In [ ]:
print(X)
print(Y)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 

In [ ]:
print(X.shape,Y.shape)

(569, 30) (569,)


In [ ]:
# Creating DataFrame in pandas for better manipulation and visualization of data
import pandas as pd
data=pd.DataFrame(breast_cancer.data, columns=breast_cancer.feature_names)

In [ ]:
data["class"]=breast_cancer.target

In [ ]:
data.head()

mean radius  mean texture  ...  worst fractal dimension  class
0        17.99         10.38  ...                  0.11890      0
1        20.57         17.77  ...                  0.08902      0
2        19.69         21.25  ...                  0.08758      0
3        11.42         20.38  ...                  0.17300      0
4        20.29         14.34  ...                  0.07678      0

[5 rows x 31 columns]

In [ ]:
# Describe gives the statistical information about numeric values in each column 
data.describe()

mean radius  mean texture  ...  worst fractal dimension       class
count   569.000000    569.000000  ...               569.000000  569.000000
mean     14.127292     19.289649  ...                 0.083946    0.627417
std       3.524049      4.301036  ...                 0.018061    0.483918
min       6.981000      9.710000  ...                 0.055040    0.000000
25%      11.700000     16.170000  ...                 0.071460    0.000000
50%      13.370000     18.840000  ...                 0.080040    1.000000
75%      15.780000     21.800000  ...                 0.092080    1.000000
max      28.110000     39.280000  ...                 0.207500    1.000000

[8 rows x 31 columns]

**Observation**
*   Mean is slightly greater and equal to the meadian values for all the columns
*   There is a big difference between 75 %tile and maximum value which shows that there are some outliers



In [ ]:
# Printing the values of target variable
print(data['class'].value_counts())

1    357
0    212
Name: class, dtype: int64


In [ ]:
print(breast_cancer.target_names)

['malignant' 'benign']


In [ ]:
# Finding the mean value of all the parametrs for both values of target variable 
data.groupby('class').mean()

mean radius  mean texture  ...  worst symmetry  worst fractal dimension
class                             ...                                         
0        17.462830     21.604906  ...        0.323468                 0.091530
1        12.146524     17.914762  ...        0.270246                 0.079442

[2 rows x 30 columns]

**Observation**



*   There is notacible difference between mean values of different parameters of dataset for both outcome







0 is for malignant and 1 is for benign

Train and test the model

In [ ]:
# Traing the model by using train_test_spli
from sklearn.model_selection import train_test_split

In [ ]:
# Splitting the data into 9:1 ratio
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.1,stratify=Y)

In [ ]:
print(Y.mean(),Y_train.mean(),Y_test.mean())

0.6274165202108963 0.626953125 0.631578947368421


In [ ]:
print(X.mean(),X_train.mean(),X_test.mean())

61.890712339519624 61.978415134531254 61.102925829941526


In [ ]:
print(X_train)

[[2.137e+01 1.510e+01 1.413e+02 ... 1.966e-01 2.730e-01 8.666e-02]
 [1.200e+01 2.823e+01 7.677e+01 ... 7.116e-02 2.447e-01 8.194e-02]
 [1.377e+01 1.327e+01 8.806e+01 ... 5.802e-02 2.823e-01 6.794e-02]
 ...
 [2.018e+01 2.397e+01 1.437e+02 ... 2.508e-01 5.440e-01 9.964e-02]
 [1.276e+01 1.884e+01 8.187e+01 ... 8.312e-02 2.744e-01 7.238e-02]
 [9.000e+00 1.440e+01 5.636e+01 ... 1.389e-02 2.991e-01 7.804e-02]]


Scaling the data for better performance

In [ ]:
# Scalling the model by uisng StandardScalar
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

Logistic Regression model
It is usefull for binary distribution

In [ ]:
# Loading the Logistic Regression Model Nad fitting the data to the model
from sklearn.linear_model import LogisticRegression
Classifier=LogisticRegression()
Classifier.fit(X_train,Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

Evaluation of model

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
# Accuracy of training data
prediction_on_training_data=Classifier.predict(X_train)
accuracy_on_training_data=accuracy_score(Y_train,prediction_on_training_data)
print("Accuracy on training data",accuracy_on_training_data)

Accuracy on training data 0.990234375


In [ ]:
# Accuracy on test data
prediction_on_test_data=Classifier.predict(X_test)
accuracy_on_test_data=accuracy_score(Y_test,prediction_on_test_data)
print("Accuracy on test data",accuracy_on_test_data)

Accuracy on test data 0.9473684210526315


Detecting wheather the patient has breast cancer in benign or malignant state

In [ ]:
input_data=(15.34,14.26,102.5,704.4,0.1073,0.2135,0.2077,0.09756,0.2521,0.07032,0.4388,0.7096,3.384,44.91,0.006789,0.05328,0.06446,0.02252,0.03672,0.004394,18.07,19.08,125.1,980.9,0.139,0.5954,0.6305,0.2393,0.4667,0.09946)
input_data_as_numpyarray=np.asarray(input_data)
input_data_reshape=input_data_as_numpyarray.reshape(1,-1)
print(input_data_reshape)

[[1.534e+01 1.426e+01 1.025e+02 7.044e+02 1.073e-01 2.135e-01 2.077e-01
  9.756e-02 2.521e-01 7.032e-02 4.388e-01 7.096e-01 3.384e+00 4.491e+01
  6.789e-03 5.328e-02 6.446e-02 2.252e-02 3.672e-02 4.394e-03 1.807e+01
  1.908e+01 1.251e+02 9.809e+02 1.390e-01 5.954e-01 6.305e-01 2.393e-01
  4.667e-01 9.946e-02]]


In [ ]:
prediction_on_input_data=Classifier.predict(input_data_reshape)
print(prediction_on_input_data)

[0]


In [ ]:
if (prediction_on_input_data[0]==0):
  print("The cancer is in malignant state")
else:
  print("The cancer is in benign state")

The cancer is in malignant state
